[project]
name = "kg-guided-codegen"
version = "0.1.0"
description = "Knowledge graph guided code generation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.3.0",
    "gitpython>=3.1.40"
]
